Added recursive include
RedHatQE/teflo pull request #107
Opened 2021-07-21 05:32 UTC by JunqiZhang0

2021-08-31 18:36 UTC, rujutashinde reviewed
Some initial review comments , looking at the code and trying to run a basic usecase

Comment 1:
This branch is working off of old code. You will need to rebase and resubmit the Pr, as the newer changes from version 1.2.3. are not there

Comment 2
In helpers.py line 1677, change this to be scenario_graph instead of streams to avoid any confusion, at this point we are not getting data streams but scenario_graph objects

```
    # Checking if include section is present and getting validated scenario stream/s
    try:
        scenario_stream = validate_render_scenario(scenario, config, vars_data)
        return scenario_stream
```
Comment 3
in teflo.py, you have not modified the use of self.scenario.
self.scenario is now a scenario_graph object. This will need to be propagated through out
in the method `self._print_header(tasklist)` it uses self.scenario thinking it is a master scenario, and looks for a name, but since it is a graph, it errors out 
```

Connected to pydev debugger (build 183.5912.18)
--------------------------------------------------
Teflo Framework v1.2.2
Copyright (C) 2021, Red Hat, Inc.
--------------------------------------------------
2021-08-31 13:23:00,474 WARNING [teflo.resources.assets.__init__:156] Groups parameter was not set for asset host1_localhost.
2021-08-31 13:25:55,753 INFO [teflo.teflo._print_header:556] 

2021-08-31 13:25:55,757 INFO [teflo.teflo._print_header:557]                                TEFLO RUN (START)                               
2021-08-31 13:25:55,762 INFO [teflo.teflo._print_header:558] -------------------------------------------------------------------------------
2021-08-31 13:25:55,766 INFO [teflo.teflo._print_header:559]  * Data Folder           : .teflo/t3vrqdsook
2021-08-31 13:25:55,770 INFO [teflo.teflo._print_header:560]  * Workspace             : .
2021-08-31 13:25:55,775 INFO [teflo.teflo._print_header:561]  * Log Level             : debug
2021-08-31 13:25:55,778 INFO [teflo.teflo._print_header:562]  * Tasks                 : ['provision']
Traceback (most recent call last):
  File "/home/rushinde/Downloads/pycharm-community-2018.3.5/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/rushinde/Downloads/pycharm-community-2018.3.5/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/rushinde/Downloads/pycharm-community-2018.3.5/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/rushinde/Downloads/pycharm-community-2018.3.5/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/rushinde/Envs/teflo_changes/bin/teflo", line 33, in <module>
    sys.exit(load_entry_point('teflo', 'console_scripts', 'teflo')())
  File "/home/rushinde/Envs/teflo_changes/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/rushinde/Envs/teflo_changes/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/rushinde/Envs/teflo_changes/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rushinde/Envs/teflo_changes/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rushinde/Envs/teflo_changes/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/rushinde/Envs/teflo_changes/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/rushinde/teflo_changes/teflo/teflo/cli.py", line 255, in run
    cbn.run(tasklist=task)
  File "/home/rushinde/teflo_changes/teflo/teflo/teflo.py", line 373, in run
    self._print_header(tasklist)
  File "/home/rushinde/teflo_changes/teflo/teflo/teflo.py", line 563, in _print_header
    self.logger.info(' * Scenario              : %s' % getattr(self.scenario, 'name'))
AttributeError: 'ScenarioGraph' object has no attribute 'name'

Process finished with exit code 1
```

2021-09-01 00:10 UTC, JunqiZhang0 commented
@rujutashinde @shay6 Thanks for the comments, but no need to look at the code too much as this is still under heavy development, everything might be changed very soon, having this pr here just for testing use.

2021-09-01 10:11 UTC, shay6 commented on teflo/teflo.py
> +        # Iterate using certain itrator, this is post-order traveral for a tree-liked graph
also, s/itrator/iterator

2021-09-20 01:53 UTC, rujutashinde requested changes
In teflo.py, I could not figure out which where we need to add the additional dotted lines to separate out the scenario names that you are printing , please do add those to make the output clearer

2021-09-20 01:53 UTC, rujutashinde commented on docs/users/definitions/include.rst
> +More Complex Examples
Scenario Graph Explanation instead of More Complex examples as heading

2021-09-20 01:53 UTC, rujutashinde commented on docs/users/definitions/include.rst
> +you can modify this by adding *INCLUDED_SDF_ITERATE_METHOD* like below:
There are two ways of executing teflo scenarios, which are __by_level and by__depth. User can modify how the scenarios are executed by changing the setting *INCLUDED_SDF_ITERATE_METHOD* in the teflo.cfg , as shown below

2021-09-20 01:53 UTC, rujutashinde commented on docs/users/definitions/include.rst
> +    included_sdf_iterate_method = by_level
it should be by_depth as by_level is set by default. Also mention that by_level is the default setting

2021-09-20 01:53 UTC, rujutashinde commented on docs/users/definitions/include.rst
> +All blocks(provision, orchestrate, execute, report) in a senario descriptor file will be executed together
All blocks(provision, orchestrate, execute, report) in a senario descriptor file will be executed together for each scenario, in case there are included scenarios

2021-09-20 01:53 UTC, rujutashinde commented on docs/users/definitions/include.rst
> +The above is an complex *include* usage
The above is an complex *include* usage. Consider sdf1-sdf13 are different included scenarios and sdf is the main scenario

2021-09-20 01:53 UTC, rujutashinde commented on docs/users/definitions/include.rst
> +All blocks(provision, orchestrate, execute, report) in a senario descriptor file will be executed together
Also mention that scenarios should be designed such that the dependent scenario should be at the lower level in the graph. In the below example if sdf13 has the provisioning information and the orchestrate block which uses these provisioned assets can be in scenario which is at a higher level, but not the other way round.

2021-09-20 01:53 UTC, rujutashinde commented on docs/users/output.rst
>    │   └── ansible_orchestrator
under invenory, it should be inventor_uuid instead of master

2021-09-20 01:53 UTC, rujutashinde commented on docs/users/output.rst
> +  └── <scenaio_filename_without_file_extension>_results.yml
<included_scenario_filename_without_file_extension>_results.yml
Also add back results.yml as it is present in the .results.folder

2021-09-20 01:53 UTC, rujutashinde commented on docs/users/output.rst
> +    *   - <scenaio_filename_without_file_extension>_results.yml
same comments as above. Add back the results.yml

2021-09-20 01:53 UTC, rujutashinde commented on teflo/core.py
> +            for host in all_hosts:
`for host in sorted(all_hosts, key=lambda h: h.name):`

Should be added back, as it allows the hosts to be added in order in the inventory. any specific reason you decided to remove this?

2021-09-20 01:53 UTC, rujutashinde commented on teflo/exceptions.py
> +from termcolor import colored
Dont all errors need to be seen in red? Right now we just have helpers and teflo error, Can we put the remaining errors in red as well? OR if you make the base error class to use red for the error message , everything inheriting it will use red ?

2021-09-20 01:53 UTC, rujutashinde commented on teflo/helpers.py
> +def preproc_path(data_folder: str) -> str:
Can you add definition of what this method is doing?

2021-09-20 01:53 UTC, rujutashinde commented on teflo/helpers.py
> +    from .resources import Scenario
add the import message on the top of the file

2021-09-20 01:53 UTC, rujutashinde commented on teflo/helpers.py
> +    from .utils.scenario_graph import ScenarioGraph
add the import message on the top of the file

2021-09-20 01:53 UTC, rujutashinde commented on teflo/teflo.py
> +        # self.cbn_inventory = Inventory(self.config, self._uid)
Remove comments lines 204-206

2021-09-20 01:53 UTC, rujutashinde commented on teflo/teflo.py
>          """
The definition should change for the included scenario logic.

2021-09-20 03:09 UTC, JunqiZhang0 commented
> In teflo.py, I could not figure out which where we need to add the additional dotted lines to separate out the scenario names that you are printing , please do add those to make the output clearer

There is already dotted lines between names

2021-09-20 03:15 UTC, JunqiZhang0 commented on teflo/core.py
> +            for host in all_hosts:
all_hosts comes from the previous level function call, it already maintains the order, so there is no need to sort it again

2021-09-20 03:15 UTC, JunqiZhang0 commented on teflo/exceptions.py
> +from termcolor import colored
Yes,all other errors are subclasses of those two errors

2021-09-20 03:17 UTC, JunqiZhang0 commented on teflo/helpers.py
> +    from .resources import Scenario
Must import these two libs here to avoid circular import for Python interpreter, I mentioned this on the line above

2021-09-20 03:17 UTC, JunqiZhang0 commented on teflo/helpers.py
> +    from .utils.scenario_graph import ScenarioGraph
same as above

2021-09-20 03:21 UTC, JunqiZhang0 commented
@rujutashinde  Thank you so much for the review, for some of the reviews, I added reply that contains explanation about why I designed it that way and marked as resolved, for all other comments which I didn't reply, I will make the changes and mark them as resolve.

2021-09-20 14:57 UTC, rujutashinde requested changes
Pointed the lines where you can add the additional dotted lines and a few commented statements to remove

2021-09-20 14:57 UTC, rujutashinde commented on teflo/teflo.py
> +            if do_validate:
Add this line before the actual statement self.logger.info("." * 50)

2021-09-20 14:57 UTC, rujutashinde commented on teflo/teflo.py
> +        self.logger.info(termcolor.colored("Validating against all scenarios!", "green"))
I think this is an extra line , as you are printing it down after checking if do_validate is set in line  369

2021-09-20 14:57 UTC, rujutashinde commented on teflo/teflo.py
> +        for sc in cleanup_sc:
Add this line before the actual statement `self.logger.info("." * 50)`

2021-09-20 14:57 UTC, rujutashinde commented on teflo/teflo.py
> +        if len(tasklist) != 0:
Add this line before the actual statement `self.logger.info("." * 50)`

2021-09-20 14:57 UTC, rujutashinde commented on teflo/teflo.py
> +            # for sc in self.scenario_graph:
remove comment

2021-09-20 14:57 UTC, rujutashinde commented on teflo/teflo.py
> +                        # for sc in self.scenario_graph:
remove comment

2021-09-20 14:57 UTC, rujutashinde commented on teflo/teflo.py
> +                # for scenario in self.scenario_graph:
remove comment

2021-09-20 18:38 UTC, JunqiZhang0 commented on teflo/teflo.py
> +        self.logger.info(termcolor.colored("Validating against all scenarios!", "green"))
This is not an extra line, this is a notice for all validate, should I delete it?

2021-09-20 18:40 UTC, JunqiZhang0 commented on teflo/teflo.py
> +            if do_validate:
This will cause something like below, are we sure to add this?
................................
.................................
info
...............................
...............................
info

2021-09-20 18:40 UTC, JunqiZhang0 commented on teflo/teflo.py
> +        for sc in cleanup_sc:
same as above

2021-09-20 18:41 UTC, JunqiZhang0 commented on teflo/teflo.py
> +        if len(tasklist) != 0:
line 490 has this line

2021-09-20 19:03 UTC, rujutashinde commented on teflo/teflo.py
> +        self.logger.info(termcolor.colored("Validating against all scenarios!", "green"))
Add a dotted line below this

2021-09-20 19:03 UTC, rujutashinde commented on teflo/teflo.py
> +            if do_validate:
u can skip this for now

2021-09-20 19:04 UTC, rujutashinde commented on teflo/teflo.py
> +        for sc in cleanup_sc:
u cna skip this for now

2021-09-20 19:07 UTC, rujutashinde reviewed
I think most of it is ok, just a couple more things , i have marked most of them resolved

2021-09-20 20:49 UTC, rujutashinde reviewed
LGTM

2021-09-22 19:53 UTC, rujutashinde commented on teflo/core.py
> +            for host in all_hosts:
Need to add this back as discussed

2021-09-23 19:26 UTC, rujutashinde approved these changes
LGTM

2021-09-23 23:30 UTC, merged