Added fix for resource ordering issue in results.yml
RedHatQE/teflo pull request #110
Opened 2021-07-21 18:30 UTC by Dannyb48

* Should resolve issue #93 where resources in the results.yml
   were ending up out of proper order when either using labels
   or resource status. It should work for both when the
   resources are need to be reloaded when blaster tasks have been
   run in parallel or sequential.

 * Also included tests to better capture the different variations

2021-07-23 03:36 UTC, rujutashinde requested changes
I tested it out with a couple of scenarios and the order is maintained
1. tested with labels and provisioning
2. tested with failed orchestrate tasks (starts correctly from the failed one)
3. tested without labels

Rest looks good, just a couple of print statements need to be removed

2021-07-28 15:11 UTC, Dannyb48 commented on teflo/resources/scenario.py
> +            print(f"loaded {item.name} at idx {idx}")
Done

2021-07-28 15:11 UTC, Dannyb48 commented on teflo/resources/scenario.py
> +                print(f"add {item.name}")
Done

2021-07-28 15:56 UTC, rujutashinde approved these changes

2021-07-28 15:56 UTC, merged