CCITCARBON-205 The import_results list for reports should be updated only when is not None
RedHatQE/teflo pull request #112
Opened 2021-07-26 14:31 UTC by shay6

2021-07-26 15:15 UTC, rujutashinde requested changes

2021-07-26 15:15 UTC, rujutashinde commented on teflo/importers/artifact_importer.py
> +            else:
the else is incorrect.
Else block is incorrect. we are checking if [None] then make it [] else it is getattr(self.plugin, 'import_results').
Also the error message should be printed irrespective of the if -else block. because we have got an exception here. So the error message is needed
 it should be 
```
else:
        setattr(self.report, 'import_results', getattr(self.plugin, 'import_results'))
raise TefloImporterError('Failed to import artifact %s' % self.report.name)
```

2021-07-26 15:42 UTC, shay6 commented on teflo/importers/artifact_importer.py
> +            else:
done

2021-07-26 15:48 UTC, rujutashinde approved these changes

2021-07-28 13:35 UTC, JunqiZhang0 approved these changes
lgtm

2021-07-28 13:41 UTC, merged