CCITCARBON-371 add skip failures ability during the graph run
RedHatQE/teflo pull request #139
Opened 2021-10-14 16:11 UTC by shay6

2021-10-14 16:35 UTC, shay6 commented on teflo/teflo.py
> +                if state is 'FAILED' and not skip_fail:
the default behavior is `skip_fail=False`, as the current situation right now. I just give the ability to skip the failures by raising the "skip_fail" flag.
If skip_fail is true, then the customer will see the exceptions and the pipeline will continue

2021-10-14 17:46 UTC, rujutashinde commented on teflo/teflo.py
> +                if state is 'FAILED' and not skip_fail:
ok i tested it out with a scenario, -sf allowed me to go ahead with an error and  not using the flag let me halt at the first error

2021-10-14 17:47 UTC, rujutashinde commented on teflo/cli.py
> +              default=False,
Do we have to mention `default=False` , as this works only when -sf is provided in the cli

2021-10-14 17:50 UTC, rujutashinde commented on teflo/cli.py
> +              help="Skip tasks failures during the scenario graph run and step forward to the"
Modify the help statement, this is not very clear what the switch is doing.
"Allows to skip the exiting teflo run during a task failure"

?

2021-10-14 17:53 UTC, rujutashinde commented on teflo/teflo.py
>                      raise TefloScenarioFailure("`%s` failed during running" % sc.name)
Please modify this statement also
`raise TefloScenarioFailure("Scenario `%s` failed during the Teflo run" % sc.name)`

2021-10-14 20:51 UTC, shay6 commented on teflo/cli.py
> +              help="Skip tasks failures during the scenario graph run and step forward to the"
will do

2021-10-15 02:07 UTC, rujutashinde commented on teflo/cli.py
> +              default=False,
i think it can stay , here is the explanation https://click.palletsprojects.com/en/8.0.x/options/#boolean-flags

2021-10-30 16:39 UTC, JunqiZhang0 requested changes

2021-10-30 16:39 UTC, JunqiZhang0 commented on docs/users/quickstart.rst
> +      -sf, --skip-fail                Allows to skip the exiting teflo run during
Better name this as ignore-fail/skip-fail: for skip **failure** during a teflo run(your logic now is skip teflo rather than skip failure)

2021-10-30 16:41 UTC, JunqiZhang0 commented on examples/docs-usage/configuration.yml
> +# Allows to skip the exiting teflo run during a task failure.
+1 for this, the explanation is not clear, should be fixed

2021-10-30 16:42 UTC, JunqiZhang0 commented on docs/users/quickstart.rst
> +      -sf, --skip-fail                Allows to skip the exiting teflo run during
the explanation is incorrect, should be fixed

2021-11-02 13:15 UTC, shay6 commented
My local branch is broken. Sorry for the mess
https://github.com/RedHatQE/teflo/pull/157

2021-11-02 13:16 UTC, closed without merging