CCITCARBON-364 Allow iterate_method from cli
RedHatQE/teflo pull request #150
Opened 2021-10-27 10:53 UTC by guyyaakov1

Added Iterate Method option from cli

2021-11-01 16:29 UTC, JunqiZhang0 commented on teflo/cli.py
> +    elif iterate_method:
This part should be added as a part of the ```elif show_graph```

2021-11-01 18:14 UTC, JunqiZhang0 requested changes

2021-11-01 18:14 UTC, JunqiZhang0 commented on teflo/teflo.py
> +    def _validate_iterate_method_option(self):
This method is not being called by any function, why do we need this? If the purpose is for unit tests, it should go to test  part

2021-11-01 19:11 UTC, rujutashinde commented on teflo/teflo.py
> +    def _validate_iterate_method_option(self):
Guy and i spoke about this , he was supposed to make changes and submit the PR again. He had put this method only for a unit test.As per our last conversation he is to remove this and provide another unit test

2021-11-01 19:12 UTC, rujutashinde requested changes
please resubmit with the changes we discussed over the meeting

2021-11-02 14:04 UTC, rujutashinde reviewed
LGTM I will let @JunqiZhang0  approve it

2021-11-02 14:52 UTC, JunqiZhang0 approved these changes
LGTM

2021-11-02 16:07 UTC, merged