CCITCARBON-372 make scenario graph size a static attribute
RedHatQE/teflo pull request #166
Opened 2021-11-17 17:36 UTC by shay6

2021-11-23 14:41 UTC, shay6 commented on teflo/utils/scenario_graph.py
> +                 passed_tasks: list = [], failed_tasks: list = [], size: int = None):
@rujutashinde I saw that all other variables have an empty value in default and I wanted to put an integer, so that's why I chose `None`.

2021-11-23 14:59 UTC, rujutashinde commented on teflo/utils/scenario_graph.py
> +                 passed_tasks: list = [], failed_tasks: list = [], size: int = None):
So if int is the type used, then default should be an int no? we will always have a graph if there is just a single scenario with one node. @JunqiZhang0  thoughts?

2021-11-23 16:00 UTC, JunqiZhang0 commented on teflo/helpers.py
> +                                   scenario_vars=root_scenario_temp_data, size=graph_size)
size should be a static attribute of Scenario Graph, which means it can not be passed from the outside, it will be dangerous to allow this attribute to be settable.(For example, you can set size to be anything from here). So you should not set it this way. The correct way could be, add up the size during the process(which you did correctly), add this attribute to each scenario(for example, add an attribute to scenario object called children_size), from scenario graph class's size method, you can just extract the children_size attribute from the root node and return children_size+1. Or any other similar solution works, anyway, you can't allow this attribute settable from outside.

2021-11-23 16:05 UTC, JunqiZhang0 requested changes

2021-11-23 16:05 UTC, JunqiZhang0 commented on teflo/utils/scenario_graph.py
> +                 passed_tasks: list = [], failed_tasks: list = [], size: int = None):
There should **not** be a default value of size, the size should be dynamic according to the real size. If there;s nothing in a scenario graph, the size should be 0, if there's one node, the size should be automatically go up to 1. So no need to set default value here. All other value are private attribute which should only be set by private method from scenario graph class, not outside.

2021-11-24 13:19 UTC, shay6 commented on teflo/utils/scenario_graph.py
> +                 passed_tasks: list = [], failed_tasks: list = [], size: int = None):
done. please take a look @JunqiZhang0

2021-11-24 13:19 UTC, shay6 commented on teflo/helpers.py
> +                                   scenario_vars=root_scenario_temp_data, size=graph_size)
done. please take a look @JunqiZhang0

2021-12-08 11:26 UTC, shay6 commented on teflo/helpers.py
> +                                   scenario_vars=root_scenario_temp_data, size=graph_size)
I increased the children_size attribute during the process. so every scenario instance holds the size of its children.

also, I'm using the size variable to count the checked_list and it represents the size of the entire ScenarioGraph.

please inform me if something is unnecessary here. @JunqiZhang0 @rujutashinde

2021-12-08 15:12 UTC, JunqiZhang0 requested changes
Please add unit test to test the children_size is correct for all scenario node, you can leverage the existing sdf structure in tests/

2021-12-08 15:12 UTC, JunqiZhang0 commented on teflo/utils/scenario_graph.py
> +        self._size = self._root.children_size
You should return self._root.children_size directly

2021-12-08 16:22 UTC, shay6 commented on teflo/utils/scenario_graph.py
> +        self._size = self._root.children_size
done

2021-12-09 05:21 UTC, JunqiZhang0 commented on teflo/utils/scenario_graph.py
> +        return self._root.children_size
Should be children size +1 as you should count the root node itself

2021-12-09 09:51 UTC, shay6 commented on teflo/utils/scenario_graph.py
> +        return self._root.children_size
but when I did debug, I saw the right size according to the checked_list size. 
In my example from above, it was already equal to 4.

2021-12-15 13:43 UTC, shay6 commented
I added the unit tests @JunqiZhang0

2022-01-06 23:50 UTC, JunqiZhang0 reviewed
The code LGTM, I will download it and test it manually then approve it

2022-01-07 13:47 UTC, JunqiZhang0 approved these changes
LGTM

2022-01-09 05:13 UTC, merged