CCITCARBON-377 Changes for ANSIBLE_EXTRA_VARS_FILES
RedHatQE/teflo pull request #167
Opened 2021-11-22 18:56 UTC by guyyaakov1

-Changes for ANSIBLE_EXTRA_VARS_FILES option for orchestrate/execute task.  -Added option to use Multiple var_file by Dir path

2021-11-22 20:21 UTC, rujutashinde requested changes

2021-11-22 20:21 UTC, rujutashinde commented on teflo/helpers.py
> +    # CHECK IF VAR_DATA WAS GIVEN BY USER IS FILE OR DIR
This is not taking into account if temp_data_raw contains file as well as a dictionary
So temp_data_raw can be multiple entries, like the example below:

`teflo run -s scenario.yml -t provision --vars-data template_file.yml --vars-data '{ "count": "2" }'`

Also Read
https://teflo.readthedocs.io/en/latest/users/variable_data.html#variable-file

Previously this worked because we were extending the variable_file_list with temp_raw_data tuple and then checking if  it is a file path or a json. With your changes the json part will never get added to the variable_file_list. 

Also when you make the edits run your teflo code branch against the teflo2_e2e_jobs in jenkins to make sure they pass, so that way u will be sure  your code works with different usecases.

2021-11-23 16:49 UTC, JunqiZhang0 commented on teflo/helpers.py
> +def check_for_var_file(config, temp_data_raw=()):
The param temp_data_raw is missed in the method documentation

2021-11-29 16:40 UTC, rujutashinde requested changes
Also update the documentation suggesting that via cli we can pass a variable file or a directory

https://teflo.readthedocs.io/en/latest/users/variable_data.html

2021-11-29 16:40 UTC, rujutashinde commented on teflo/helpers.py
> +                if json.loads(tempjson):
here tempjson is being used before declaration, 
you are doing json loads twice in line 1388 and 1389

does this work? have you tested it with user supplied data of json tuple and also file/dir ?

2021-11-30 22:40 UTC, rujutashinde commented on docs/users/variable_data.rst
> +--------
The dotted lines should be under the entire heading

2021-12-08 18:35 UTC, rujutashinde requested changes

2021-12-08 18:35 UTC, rujutashinde commented on tests/functional/test_cli.py
> +                     '-d', '/tmp', '--vars-data', '../assets/vars_files']
In this test you are passing --vars-data '../assets/var_files'  directory which has two files with variables 'nametwo'  and 'somekey', they are not being called in the single_template.yml SDF.
The test is passing because it uses the default variable space which is assets/vars_data.yml  which has the variable asset_name: unit_test and hence the assert 'unit_test' in results.output is passing

You need to verify that the two new variables that you added in the directory are getting passed. So create a new SDF file and use these two variables  OR modify the single_template.yml to use the two variables something like this:

`---
name: descriptor
description: descriptor

credentials:
  - name: provider

include:

provision:
  - name: {{ asset_name | default('test') }}
    provider:
      name: openstack

  - name: {{ somevkey | default('test1') }}
    provider:
      name: openstack

  - name: {{ nametwo | default('test2') }}
    provider:
      name: openstack

orchestrate:

execute:

report:

notifications:
`

And then test the asserion to chekc if the new variable values are getting replaced in the output

2021-12-09 14:46 UTC, rujutashinde requested changes

2021-12-09 14:46 UTC, rujutashinde commented on tests/functional/test_cli.py
> +        assert 'is a directory' in results.output
What is "is a directory" ?  you are still not checking if the 2 variables in ../assets/var_files are substituted when you use the scenario_graph_basic_test.yml SDF file.

2021-12-09 15:15 UTC, rujutashinde commented on tests/assets/scenario_graph_basic_test/sdf.yml
> +  - name: {{ somevkey | default('test1') }}
spelling mistake somekey

2021-12-09 16:44 UTC, rujutashinde requested changes

2021-12-09 16:44 UTC, rujutashinde commented on tests/functional/test_cli.py
> +        assert '/vars_files/vardata.yml' in res[0]
Change assert '/vars_files/vardata.yml' in res[0] 
assert '/vars_files/vardatatwo.yml' in res[1]

to :
assert 'firstval' in results.output
assert 'secondval' in results.output

2022-01-05 16:08 UTC, rujutashinde requested changes
needs more work

2022-01-05 16:08 UTC, rujutashinde commented on teflo/ansible_helpers.py
>              var_files_list = check_for_var_file(self.config)
Now that we already are updating the EXTRA_VARS_LIST in the config. we dont need to call the check_for_var_file method again. It gets called in the beginning and we are updating the config[EXTRA_VARS_FILES] there

2022-01-05 16:08 UTC, rujutashinde commented on teflo/ansible_helpers.py
> +from .constants import EXTRA_VARS_FILES
this should not be necessary if you are modifing the config. look the other comments in helpers.py

2022-01-05 16:08 UTC, rujutashinde commented on teflo/ansible_helpers.py
> +            var_files_list.append(EXTRA_VARS_FILES)
var_files_list.append(self.config.get('EXTRA_VARS_FILES')

2022-01-05 16:08 UTC, rujutashinde commented on tests/functional/test_cli.py
> +    @staticmethod
is this test working?

2022-01-06 13:14 UTC, guyyaakov1 commented on teflo/helpers.py
> +                                EXTRA_VARS_FILES.append(filepath)
I placed it there because i think that if it will be at the end it will append the whole "var_file_list" and not just the cli input.

2022-01-06 13:55 UTC, guyyaakov1 commented on tests/functional/test_cli.py
> +    @staticmethod
Yes

2022-01-10 00:00 UTC, rujutashinde commented on teflo/helpers.py
> +                                DEFAULT_CONFIG["EXTRA_VARS_FILES"].append(filepath)
This still needs to change, as per what we spoke.
You dont have to use DEFAULT_CONFIG but the config passed to this method

Also the config needs to be updated at the end and not at the if /else block

2022-01-10 00:00 UTC, rujutashinde commented on teflo/helpers.py
> +from .constants import PROVISIONERS, RULE_HOST_NAMING, TASKLIST, NOTIFYSTATES, DEFAULT_CONFIG
you should not need DEFAULT_CONFIG

2022-01-10 15:41 UTC, rujutashinde requested changes
The ansible_helpers.py is not added? you need to make the change in this file to make sure the ansible playbooks can get the variables/variable files from the config location now

Were you able to run the scenario i had provided doe sit run successfully?

2022-01-10 15:42 UTC, rujutashinde commented on teflo/ansible_helpers.py
>              var_files_list = check_for_var_file(self.config)
you dont need this line. you dont have to call this function again.

2022-01-11 14:38 UTC, rujutashinde requested changes
Some minor comments to be removed/added.
Does this code pass with unit test you added as well as the scenario that we were running yesterday?

2022-01-11 14:38 UTC, rujutashinde commented on teflo/helpers.py
> +    json_val_list = []
Add a comment line what this list is for

2022-01-11 14:38 UTC, rujutashinde commented on teflo/helpers.py
> +    config_var_list = deepcopy(var_file_list)
Add a comment line what/how you are updating the config and the json values separately.
This will help anyone who looks at the code

2022-01-11 14:38 UTC, rujutashinde commented on teflo/ansible_helpers.py
> +            # var_files_list = check_for_var_file(self.config)
remove this commented line

2022-01-11 15:22 UTC, merged