remote inclusion
RedHatQE/teflo pull request #168
Opened 2021-11-24 01:37 UTC by JunqiZhang0

1. Finished the implementation for remote inclusion(first version)
2. Documentation

2021-12-03 18:28 UTC, rujutashinde commented on docs/users/definitions/include.rst
> +If you want to use jinja templating for __include__ section, you can set a parameter called __toggle_jinja_include__ to be true, under __defaults__ section in teflo.cfg
this example is for jinja templating for include?

2021-12-03 18:28 UTC, rujutashinde commented on teflo/helpers.py
> +    # deepcopy will work only under pythonversion > 3.9
Does that mean this will break for python 3.6

2021-12-03 18:28 UTC, rujutashinde commented on teflo/helpers.py
> +                cmd = 'git clone ' + url + ' ' + config["REMOTE_LIB_DOWNLOAD_LOCATION"] + short_name_of_lib
Need to make sure config["REMOTE_LIB_DOWNLOAD_LOCATION"] is a directory , so need to take care of the '/' in the end as discussed

2021-12-03 18:28 UTC, rujutashinde commented on teflo/helpers.py
> +                # all remote libraries should be stored in the same place (root_workspace/.teflo_library)
it should be (root_workspace/.teflo_libraries)

2021-12-08 05:27 UTC, rujutashinde requested changes

2021-12-08 05:27 UTC, rujutashinde commented on docs/users/definitions/include.rst
> +You can include teflo workspace from remote server(currently only support git)
currently only support for git

2021-12-08 05:27 UTC, rujutashinde commented on teflo/resources/scenario.py
> +        """Set report property."""
remove report property

2021-12-08 05:27 UTC, rujutashinde commented on teflo/resources/scenario.py
> +    def library(self):
are we not changing the property name to remote_workspace? since we changed the key in the SDF to be remote_workspace from libraries?

2021-12-08 05:27 UTC, rujutashinde commented on teflo/resources/scenario.py
> +        profile['library'] = self.library
this  should be profile['remote_workspace'] rlse it will not print the results.yml correctly

2021-12-08 15:12 UTC, rujutashinde commented on teflo/orchestrators/ext/ansible_orchestrator_plugin/ansible_orchestrator_plugin.py
> +                    self.config["WORKSPACE"], self.script.get('name').split(' ', 1)[0])):
@JunqiZhang0  Will you be changing this? it is ok if you want to leave it for now and then refactor this in later PR, if you think it will add additional testing.

2021-12-08 15:24 UTC, JunqiZhang0 commented on teflo/orchestrators/ext/ansible_orchestrator_plugin/ansible_orchestrator_plugin.py
> +                    self.config["WORKSPACE"], self.script.get('name').split(' ', 1)[0])):
I would leave it for now and refactor it later

2021-12-08 22:53 UTC, rujutashinde commented on teflo/teflo.py
> +        if self.config["CLEAN_CACHED_WORKSPACE_AFTER_EACH_RUN"] == "True":
Need to change this to
`if self.config["CLEAN_CACHED_WORKSPACE_AFTER_EACH_RUN"].lower() == "true":`

if the user puts it in CAPS it is not accounted for

2021-12-09 14:55 UTC, rujutashinde commented on teflo/teflo.py
> +        if self.config["CLEAN_CACHED_WORKSPACE_AFTER_EACH_RUN"].lower() == "True":
this needs to be true not True else it will still fail as lower will turn everything to "true" not "True"

2021-12-09 15:57 UTC, merged