fixed resource name issue
RedHatQE/teflo pull request #187
Opened 2022-01-20 11:55 UTC by JunqiZhang0

2022-01-24 18:34 UTC, rujutashinde reviewed
Is it possible to add a unit test for this change?
something to check if the resources are same or different based on the resource id?
I do think unit tests is important to cover this

Rest looks good.

i tested with the below scenario which ran fine
`---

name: data_folder
description:

provision:
  - name: laptop
    groups: localhost
    ip_address: 127.0.0.1
    ansible_params:
      ansible_connection: local

execute:

  - name: ex1
    description: "Test running script during execute"
    executor: runner
    hosts: localhost
    shell:
    - chdir: /home
      command: ls
    artifacts:
      - ./cnv-ibm_bare_metal-tests.xml
      - ./payload_1/results/junit_example.xml


  - name: ex1
    description: "Test running script during execute"
    executor: runner
    hosts: localhost
    shell:
    - chdir: /home
      command: ls


report:
  - name: SampleTest.xml
    description: import results to polarion
    credential: polarion-creds
    importer: polarion
    project_id: Carbon1
    testsuite_properties:
      polarion-lookup-method: name
      polarion-testrun-title: e2e-tests

  - name: SampleTest.xml
    description: import results to polarion
    credential: polarion-creds
    importer: polarion
    project_id: Carbon1
    testsuite_properties:
      polarion-lookup-method: name
      polarion-testrun-title: test2
~                                                                                                                                                                                                                                                                                                                            
~                                               `

2022-01-25 06:39 UTC, JunqiZhang0 commented
> Is it possible to add a unit test for this change? something to check if the resources are same or different based on the resource id? I do think unit tests is important to cover this
> 
> Rest looks good.
> 
> i tested with the below scenario which ran fine `---
> 
> name: data_folder description:
> 
> provision:
> 
> * name: laptop
>   groups: localhost
>   ip_address: 127.0.0.1
>   ansible_params:
>   ansible_connection: local
> 
> execute:
> 
> * name: ex1
>   description: "Test running script during execute"
>   executor: runner
>   hosts: localhost
>   shell:
>   
>   * chdir: /home
>     command: ls
>     artifacts:
>     
>     * ./cnv-ibm_bare_metal-tests.xml
>     * ./payload_1/results/junit_example.xml
> * name: ex1
>   description: "Test running script during execute"
>   executor: runner
>   hosts: localhost
>   shell:
>   
>   * chdir: /home
>     command: ls
> 
> report:
> 
> * name: SampleTest.xml
>   description: import results to polarion
>   credential: polarion-creds
>   importer: polarion
>   project_id: Carbon1
>   testsuite_properties:
>   polarion-lookup-method: name
>   polarion-testrun-title: e2e-tests
> * name: SampleTest.xml
>   description: import results to polarion
>   credential: polarion-creds
>   importer: polarion
>   project_id: Carbon1
>   testsuite_properties:
>   polarion-lookup-method: name
>   polarion-testrun-title: test2
>   ~
>   ~                                               `

Cool, If everything worked fine I'll add it, thank you very much for testing!

2022-01-26 14:15 UTC, rujutashinde requested changes
you need to squash the commits

2022-01-26 14:15 UTC, rujutashinde commented on teflo/core.py
> +    @resource_id.setter
i realized this when i saw your unit test, we should not be setting resource_id. It should be auto generated. So the setter should throw an error stating resource_id cannot be set.
Something like this 
`    @groups.setter
    def groups(self, value):
        """Set groups property."""
        raise AttributeError('You cannot set the groups after asset class is '
                             'instantiated.')`

Also this will force you to change the unit test where you are setting the id.

2022-01-26 14:15 UTC, rujutashinde commented on tests/functional/test_resources.py
> +    def test_action_creation_with_resource_id_defined():
This test should assert the error message that resource id cannot be set

2022-01-26 14:15 UTC, rujutashinde commented on tests/functional/test_resources.py
> +    def test_action_creation_with_resource_id_not_defined():
same thing as above

2022-01-26 15:23 UTC, JunqiZhang0 commented on teflo/core.py
> +    @resource_id.setter
Why should we forbid this?

2022-01-26 16:00 UTC, rujutashinde commented on teflo/core.py
> +    @resource_id.setter
resource id should not be changed in between, it is a unique id and the system should generate this. it is not something the user should be able to provide or the program to alter in between

2022-01-27 16:59 UTC, rujutashinde requested changes

2022-01-27 16:59 UTC, rujutashinde commented on tests/functional/test_resources.py
> +    def test_report_creation_with_resource_id_defined():
So this test can either be modified to such that you are trying to set the resource id for action , and you get the error that "you cannot define resource id after class instantiation" OR remove it completely because setting it to a random id and then verifying that it is not the same, is some what same as what the below unit test is doing where you are checking resource id is not none

2022-01-27 16:59 UTC, rujutashinde commented on tests/functional/test_resources.py
> +    def test_action_creation_with_resource_id_not_defined():
name of the unit test should be appropriate or provide what the unit test is doing u are verifying that resource id is getting genrated

2022-01-27 16:59 UTC, rujutashinde commented on tests/functional/test_resources.py
> +    def test_action_creation_with_resource_id_not_defined():
name of this test should be different you are testing that the resource id is generated

2022-01-27 16:59 UTC, rujutashinde commented on tests/functional/test_resources.py
> +    def test_report_creation_with_resource_id_defined():
Also these are same test as above you are not changing it to a report resource

2022-01-28 15:02 UTC, rujutashinde approved these changes

2022-01-28 15:21 UTC, merged