CCITCARBON-369 Allow Ansible playbooks stored within a collection to be defined within a orchestrate action
RedHatQE/teflo pull request #190
Opened 2022-01-27 11:41 UTC by guyyaakov1

2022-01-28 12:41 UTC, JunqiZhang0 requested changes
Please add unit test and integration test to prove this works

2022-01-31 20:54 UTC, Dannyb48 commented
Just my 2 cents since my team is also dependent on this feature. I would go back to the original RFE and confirm that the sample use cases supplied actually work. :)

From looking at this initial implementation it seems like I would have to supply the absolute path to the playbook in the collection using FQCN format <ansible.collection.path.in.ansible.config.namespace.collection.subdirectory.playbook>

Some things to confirm are

-  Do you need to look up what the ansible collections pathes are? Do you need to check all default/specified pathes to make sure you've check all the places? Then do you need to build an absolute path before checking if it is a file. [1]

- If you do this conversion and store it, does the ansible-playbook command let you call it directly like that or does it have to be in the FQCN notation [2]

[1] https://docs.ansible.com/ansible/latest/reference_appendices/config.html#collections-paths
[2] https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#using-a-playbook-from-a-collection

2022-03-14 12:58 UTC, shay6 commented on tests/localhost_scenario/collections/ansible_collections/ryankwilliams/collections_learning/MANIFEST.json
> +{
same

2022-03-29 13:26 UTC, rujutashinde requested changes

2022-03-29 13:26 UTC, rujutashinde commented on teflo/ansible_helpers.py
> +        """ in case of using fqcn We calling this function to look for the
Change the staring line to this: This method is used while looking for the playbook path using fqcn

2022-03-29 13:26 UTC, rujutashinde commented on teflo/ansible_helpers.py
> +        col_cfg_path = config['defaults']['collections_paths']
config.get('defaults').get('collections_path')
This allows you to get a none value in case collections_path is not provided by the ansible.cfg

2022-03-29 13:26 UTC, rujutashinde commented on teflo/ansible_helpers.py
> +        col_cfg_path = ''.join(col_cfg_path.split('.', 1))
check if col_cfg_path is not None then do the join operation

2022-03-29 13:26 UTC, rujutashinde commented on teflo/ansible_helpers.py
> +                    if new_playbook_path:
why do we need to check here if the new_playbook_path is present? you should directly be able to return the `new_playbook_path`

2022-03-29 13:26 UTC, rujutashinde commented on teflo/ansible_helpers.py
> +        else:
you need to have a return here correct? what happens when it gets into the else block?

2022-03-29 13:26 UTC, rujutashinde commented on teflo/ansible_helpers.py
> +        :param config: get ansible.cfg file
the param listed out here are not really being passed to the method. you are using them from what is defined in the class. So you dont need to mention it here, in the description

2022-03-29 13:44 UTC, rujutashinde commented
Also there is unit test missing for the anisble _helpers.py new method to test when path is found and when path is not found

2022-03-30 16:22 UTC, rujutashinde approved these changes
LGTM

2022-04-05 13:39 UTC, JunqiZhang0 commented
Please add documentation

2022-04-06 13:28 UTC, rujutashinde requested changes
@guyyaakov1  have you tried to run make-docs and checked the html that gets generated? to make sure the documentaion looks ok as an user would see it?

2022-04-06 13:28 UTC, rujutashinde commented on docs/users/definitions/orchestrate.rst
> +We can Use playbook within a collection with fqcn.
Put the full form of FCQN (Fully Qualified Collections Name"

2022-04-06 13:28 UTC, rujutashinde commented on docs/users/quickstart.rst
> +Run Playbook From A Collection
I dont think the quickstart.rst needs this information. Remove this from here

2022-04-06 13:28 UTC, rujutashinde commented on docs/users/quickstart.rst
> +Please view `Using FQCN <./definitions/fqcn.html#using_playbook_from_a_collection>`__ to know more.
Thi sis important please put this in the orchestrate.rst

2022-04-06 13:28 UTC, rujutashinde commented on examples/docs-usage/template.yml
> +   # use FQCN and collection install
is this formatting ok?

2022-04-12 19:02 UTC, rujutashinde commented on docs/users/definitions/orchestrate.rst
> +
You were supposed to add a link to ansible docs here which tells you about  running playbook from collections. You had added that in quickstart.rst which  you can to put here as a note

2022-04-13 15:26 UTC, rujutashinde approved these changes

2022-04-13 15:48 UTC, JunqiZhang0 approved these changes

2022-04-13 16:01 UTC, merged