CCITCARBON-385 support of git ssh to clone remotes
RedHatQE/teflo pull request #220
Opened 2022-04-25 09:09 UTC by guyyaakov1

added use of GIT_SSH_COMMAND env_var

2022-06-10 17:40 UTC, JunqiZhang0 requested changes
Please resolve conflict

2022-06-10 17:40 UTC, JunqiZhang0 commented on .github/workflows/remote_run_u_t.yml
> +name: remote_tests
Please use github env secret for the private key

2022-07-20 17:09 UTC, rujutashinde requested changes

2022-07-20 17:09 UTC, rujutashinde commented on examples/docs-usage/include.yml
>    - workspace_url: git@github.com:dno-github/remote-teflo-lib1.git
Can you also add another example where you can provide the workspace_url using the ssh 
so  you write that if user wants to use the ssh method, then set the cfg as below
the setting in teflo.cfg  in example

and below that  what would the workspace_url look like

2022-07-21 13:29 UTC, rujutashinde approved these changes

2022-07-21 13:35 UTC, merged