WIP - CCITCARBON-379 Notifications with on_start triggers do not work correctly
RedHatQE/teflo pull request #238
Opened 2022-08-09 16:07 UTC by shay6

Right now, the on_start trigger works only on the first task in the scenario.

2022-08-23 09:43 UTC, shay6 commented
FYI
If there is no on_tasks field in notify section, then it will notify for all tasks and will be equal to:

on_tasks = ["validate", "provision", "orchestrate", "execute", "report", "cleanup"] 
Even if there is no such tasks in the scenario. For example, if we are not using report task in the scenario, it will try to run notify for report.

So I had to add a function to check for every task if it's exist in the scenario.

**Important note:** we will get the correct amount of notification only with **one** on_start notification in the current scenario

2022-08-23 12:07 UTC, shay6 commented
@JunqiZhang0 @rujutashinde 
The below tests failed:
test_cli.py::TestCli::test_remote_include
test_teflo.py::TestTeflo::test_collected_group_vars

But it's not part of the code I changed!
I think these unit tests are the cause of why we can't run the unit-tests more than one time. 
See here the [issue](https://github.com/RedHatQE/teflo/issues/188) of the unit-tests

2022-08-23 13:58 UTC, rujutashinde requested changes
need to make sure unit tests are passing

2022-08-23 13:58 UTC, rujutashinde commented on teflo/helpers.py
> +def get_task_in_scenario(task, scenario):
Please add description of what this method does

2022-08-23 13:58 UTC, rujutashinde commented on teflo/helpers.py
> +        on_tasks_exist_in_scenario = [i for i in on_tasks_exist_in_scenario if i]
i am not certain this statement is doing anything? you are looking if `i` is in the list and then assigning `i` back to the list?

why will the `on_tasks_exist_in_scenario` have an empty string?

2022-08-23 14:54 UTC, shay6 commented on teflo/helpers.py
> +        on_tasks_exist_in_scenario = [i for i in on_tasks_exist_in_scenario if i]
The function `get_task_in_scenario` is checking if some task is actually existing in the scenario and if not, then it returns an empty string. That's why I need to remove empty strings from the list.
Using this List Comprehension, it returns a new list without the empty strings.

2022-08-23 17:09 UTC, rujutashinde commented on teflo/helpers.py
> +        on_tasks_exist_in_scenario = [i for i in on_tasks_exist_in_scenario if i]
so instead of doing an additional  list comprehension, just check if the value of `get_task_in_scenario(task, scenario)` is not a empty string or change it to None and check if it is not None and then only add  it to the `on_tasks_exist_in_scenario` list

2022-08-24 13:53 UTC, shay6 commented on teflo/helpers.py
> +        on_tasks_exist_in_scenario = [i for i in on_tasks_exist_in_scenario if i]
done

2022-08-24 13:53 UTC, shay6 commented on teflo/helpers.py
> +def get_task_in_scenario(task, scenario):
done

2022-08-24 14:01 UTC, rujutashinde reviewed
just a small typo, but would like to see the demos before the merge

2022-08-25 07:06 UTC, shay6 commented on teflo/helpers.py
> +    If it's not exist the return value is None, if it's exist, the return value is
done

2022-08-31 12:39 UTC, shay6 commented
@rujutashinde @JunqiZhang0 
With this change, everything works as expected with this `on_start` feature.

I tested it with one notification and with multiple notifications.
With and without `on_tasks` field. 
I executed it also with specific tasks and without, like below:
```
teflo run -s on_start_all.yml -t provision -t execute
teflo run -s on_start_all.yml
```

2022-08-31 12:49 UTC, shay6 commented
> need to make sure unit tests are passing

2022-09-01 15:17 UTC, shay6 commented on teflo/utils/pipeline.py
> +    def get_pipeline(task, current_task):
Yes, we need the `current_task` only for notification pipeline. So I'll set the default value to `None`.
Right now, I think we don't need the `current_task` info in our regular non notification pipeline.

2022-09-13 15:05 UTC, rujutashinde approved these changes

2022-09-19 14:53 UTC, merged