Improvements to downloading ansible roles/collections
RedHatQE/teflo pull request #239
Opened 2022-08-29 18:36 UTC by ryankwilliams

# Change

This PR enables automatic retries when attempting to download ansible dependencies (roles or collections). Today, this is not enabled by default. The user needs to pass `retry` in their ansible options in order to do one retry attempt. Even if teflo fails to download roles, teflo still continues on. Resulting in playbooks failing to run at a later point due to missing dependencies (e.g. roles or collections).

Below is a list of changes provided by this PR.

Includes:
1. Include retry attempts by default. Previously this was only enabled
   when passing the `retry` flag with your ansible options. If it
   failed, it would attempt the retry one more time.
2. Do not allow teflo to carry on when ansible requirements were not
   downloaded successfully. This removes the potential playbook errors
   at a later point, when its unable to locate a collection or role.
3. Update/add new error messages to help make it easier for the user to
   understand why it failed to download ansible requirements.
4. Reduce code duplication for download_roles method.

# Verification

1. Invalid roles or collections in requirements file.

```
(venv) [rywillia@t14s mock_openshift]$ teflo run -t validate -s $TEFLO_SDF
--------------------------------------------------
Teflo Framework v2.2.6
Copyright (C) 2022, Red Hat, Inc.
--------------------------------------------------
2022-08-29 13:52:05,614 WARNING Scenario workspace was not set, therefore the workspace is automatically assigned to the current working directory. You may experience problems if files needed by teflo do not exists in the scenario workspace.
2022-08-29 13:52:05,776 INFO 

2022-08-29 13:52:05,776 INFO                                TEFLO RUN (START)                               
2022-08-29 13:52:05,776 INFO -------------------------------------------------------------------------------
2022-08-29 13:52:05,776 INFO  * Data Folder           : ./.teflo/446uodc5za
2022-08-29 13:52:05,777 INFO  * Workspace             : /home/rywillia/work/rywillia/pit/scenarios/mock_openshift/venv/mock_openshift
2022-08-29 13:52:05,777 INFO  * Log Level             : info
2022-08-29 13:52:05,777 INFO  * Tasks                 : ['validate']
2022-08-29 13:52:05,777 INFO  * Iterate Method        : by_level
2022-08-29 13:52:05,778 INFO  * Scenario              : resource_check
2022-08-29 13:52:05,778 INFO  * Scenario              : provision_base
2022-08-29 13:52:05,778 INFO  * Scenario              : orchestrate_base
2022-08-29 13:52:05,778 INFO  * Scenario              : orchestrate
2022-08-29 13:52:05,779 INFO  * Scenario              : orchestrate_install_openshift
2022-08-29 13:52:05,779 INFO  * Scenario              : execute
2022-08-29 13:52:05,779 INFO  * Scenario              : Layered product OpenShift unit test scenario
2022-08-29 13:52:05,779 INFO -------------------------------------------------------------------------------

2022-08-29 13:52:05,780 INFO Validating against all scenarios!
2022-08-29 13:52:05,780 INFO ..................................................
2022-08-29 13:52:05,780 INFO ..................................................
2022-08-29 13:52:05,781 INFO 'resource_check' is validated from the scenario file: resource_check.yml
2022-08-29 13:52:05,781 INFO ..................................................
2022-08-29 13:52:05,781 INFO ..................................................
2022-08-29 13:52:05,781 INFO 'resource_check' is running from the scenario file: resource_check.yml
2022-08-29 13:52:05,782 INFO ..................................................
2022-08-29 13:52:05,783 INFO  * Task    : validate
2022-08-29 13:52:05,784 INFO ..................................................
2022-08-29 13:52:05,784 INFO Starting tasks on pipeline: validate
2022-08-29 13:52:05,785 INFO --> Blaster v0.5.0 <--
2022-08-29 13:52:05,785 INFO Task Execution: Sequential
2022-08-29 13:52:05,785 INFO Tasks:
2022-08-29 13:52:05,786 INFO 1. Task     : resource_check
                                Class    : <class 'teflo.tasks.validate.ValidateTask'>
                                Methods  : ['run']
2022-08-29 13:52:05,786 INFO ** BLASTER BEGIN **
2022-08-29 13:52:05,787 INFO Validating <class 'teflo.resources.scenario.Scenario'> (resource_check)
2022-08-29 13:52:05,788 INFO Running validation using user provided playbook/scripts
2022-08-29 13:52:05,790 INFO Install roles using requirements file /home/rywillia/work/rywillia/pit/scenarios/mock_openshift/venv/mock_openshift/ansible/requirements.yml
2022-08-29 13:52:06,173 INFO Skipping install, no requirements found
2022-08-29 13:52:06,231 INFO Roles installed from requirements file /home/rywillia/work/rywillia/pit/scenarios/mock_openshift/venv/mock_openshift/ansible/requirements.yml!
2022-08-29 13:52:06,231 INFO Install collections using requirements file /home/rywillia/work/rywillia/pit/scenarios/mock_openshift/venv/mock_openshift/ansible/requirements.yml
2022-08-29 13:52:06,650 INFO Starting galaxy collection install process
2022-08-29 13:52:06,653 INFO Process install dependency map
2022-08-29 13:52:07,183 ERROR Failed to install collections from requirements file /home/rywillia/work/rywillia/pit/scenarios/mock_openshift/venv/mock_openshift/ansible/requirements.yml. Error: Cloning into '/home/rywillia/.ansible/tmp/ansible-local-167590bg4yig52/tmp98s5sb5r/ansible_collectionhzjipz2b'...
error: pathspec 'main22' did not match any file(s) known to git
ERROR! Failed to switch a cloned Git repo `https://gitlab.cee.redhat.com/PIT/ansible_collection.git` to the requested revision `main22`.

2022-08-29 13:52:37,216 INFO Install roles using requirements file /home/rywillia/work/rywillia/pit/scenarios/mock_openshift/venv/mock_openshift/ansible/requirements.yml
2022-08-29 13:52:37,659 INFO Skipping install, no requirements found
2022-08-29 13:52:37,719 INFO Roles installed from requirements file /home/rywillia/work/rywillia/pit/scenarios/mock_openshift/venv/mock_openshift/ansible/requirements.yml!
2022-08-29 13:52:37,719 INFO Install collections using requirements file /home/rywillia/work/rywillia/pit/scenarios/mock_openshift/venv/mock_openshift/ansible/requirements.yml
2022-08-29 13:52:38,111 INFO Starting galaxy collection install process
2022-08-29 13:52:38,114 INFO Process install dependency map
2022-08-29 13:52:38,715 ERROR Failed to install collections from requirements file /home/rywillia/work/rywillia/pit/scenarios/mock_openshift/venv/mock_openshift/ansible/requirements.yml. Error: Cloning into '/home/rywillia/.ansible/tmp/ansible-local-167896sijrrqhj/tmpthprngdm/ansible_collection0bgq7d0l'...
error: pathspec 'main22' did not match any file(s) known to git
ERROR! Failed to switch a cloned Git repo `https://gitlab.cee.redhat.com/PIT/ansible_collection.git` to the requested revision `main22`.

2022-08-29 13:52:38,716 ERROR Failed to validate resource_check
2022-08-29 13:52:38,717 ERROR A exception was raised while processing task: resource_check method: run
Traceback (most recent call last):
  File "/home/rywillia/work/ryankwilliams/teflo/teflo/utils/resource_checker.py", line 86, in __check_custom_resource
    self.ans_service.download_roles()
  File "/home/rywillia/work/rywillia/pit/scenarios/mock_openshift/venv/lib64/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/rywillia/work/rywillia/pit/scenarios/mock_openshift/venv/lib64/python3.10/site-packages/retry/api.py", line 90, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "/home/rywillia/work/rywillia/pit/scenarios/mock_openshift/venv/lib64/python3.10/site-packages/retry/api.py", line 35, in __retry_internal
    return f()
  File "/home/rywillia/work/ryankwilliams/teflo/teflo/ansible_helpers.py", line 495, in download_roles
    raise AnsibleServiceError(message)
teflo.exceptions.AnsibleServiceError: Failed to install collections from requirements  [...]

2022-08-30 13:59 UTC, rujutashinde requested changes
doc changes else LGTM

2022-08-30 13:59 UTC, rujutashinde commented on teflo/constants.py
> +# Default retries for installing ansible dependencies
Could you add documentation on these two options, as mentioned in the above comment

2022-08-30 13:59 UTC, rujutashinde commented on docs/users/definitions/orchestrate.rst
> -
Since the retry option is now removed, will the parameters be configurable by teflo users ?
`ANSIBLE_GALAXY_INSTALL_DELAY = 30
ANSIBLE_GALAXY_INSTALL_ATTEMPTS = 2`
or we would consider making them configurable via teflo.cfg? 

because the retry option was just trying once to download the roles/collections

Could you please add documentation on how to set them (if configurable )  and/or that the default values will be 30 and 2 respectively for 
`ANSIBLE_GALAXY_INSTALL_DELAY  `and `ANSIBLE_GALAXY_INSTALL_ATTEMPTS`

2022-08-30 15:35 UTC, JunqiZhang0 reviewed
LGTM for the rest

2022-08-30 15:35 UTC, JunqiZhang0 commented on teflo/orchestrators/ext/ansible_orchestrator_plugin/ansible_orchestrator_plugin.py
> +                    raise TefloOrchestratorError("Failed to download ansible roles/collections")
You should remove this try catch if you will throw error anyway

2022-08-30 15:35 UTC, JunqiZhang0 commented on teflo/utils/resource_checker.py
> +                    raise TefloError("Failed to download ansible roles/collections")
Same as above, should remove the try catch if you need to throw exception anyway

2022-08-30 20:54 UTC, ryankwilliams commented on teflo/orchestrators/ext/ansible_orchestrator_plugin/ansible_orchestrator_plugin.py
> +                    raise TefloOrchestratorError("Failed to download ansible roles/collections")
Good call @JunqiZhang0, will make the change.

2022-08-30 20:54 UTC, ryankwilliams commented on teflo/utils/resource_checker.py
> +                    raise TefloError("Failed to download ansible roles/collections")
Good call @JunqiZhang0, will make the change.

2022-08-30 21:54 UTC, ryankwilliams commented on docs/users/definitions/orchestrate.rst
> -
With this implementation, it is not configurable by the user. I did some initial investigation into seeing if it could be configurable via the teflo.cfg file. Though it won't be a quick change. Since this retry mechanism is a decorator around the `download_roles` method, it does not easily have access to the `config` attribute which contains the entire teflo configuration file contents.

For now, I think teflo should just automatically retry for the user based on its default settings. I will add documentation for the users. So they are aware of how the ansible galaxy mechanism works. How does this sound @rujutashinde?

2022-08-30 21:55 UTC, ryankwilliams commented on teflo/constants.py
> +# Default retries for installing ansible dependencies
Yes, I can.

2022-08-31 14:10 UTC, ryankwilliams commented
Hi @rujutashinde, I have addressed all comments. Please let me know if anything else is needed. Thanks!

2022-08-31 14:33 UTC, rujutashinde commented on docs/users/definitions/orchestrate.rst
> -
this sounds good

2022-08-31 14:35 UTC, rujutashinde approved these changes
LGTM

2022-09-07 20:30 UTC, rujutashinde commented
@ryankwilliams sorry for the delay ,if you can rebase  the branch i will merge this change

2022-09-07 20:39 UTC, merged