CCITCARBON-389 Support of Teflo aliases.
RedHatQE/teflo pull request #249
Opened 2022-10-06 13:52 UTC by guyyaakov1

Added support of Teflo aliases.

2022-10-06 13:54 UTC, guyyaakov1 commented
Need To Update the tests, Please let me know if you have a comment.

2022-10-06 17:33 UTC, guyyaakov1 commented
Added Unit Tests.

2022-10-10 12:30 UTC, jbpratt commented on docs/users/quickstart.rst
> +      aliase    Run Predefine command from teflo.cfg
```suggestion
      alias    Run Predefine command from teflo.cfg
```

`aliase` should by `alias`

2022-10-14 23:34 UTC, rujutashinde requested changes

2022-10-14 23:34 UTC, rujutashinde commented on docs/users/quickstart.rst
> +Aliases
Modify this to Alias , its much easier to put together and provides same information

2022-10-14 23:34 UTC, rujutashinde commented on docs/users/quickstart.rst
> +    [aliases]
[alias]

2022-10-14 23:34 UTC, rujutashinde commented on teflo/cli.py
> +@click.option("-al", "--get-aliases",
can this be -al, --alias instead of get-aliases

2022-10-14 23:34 UTC, rujutashinde commented on teflo/constants.py
> +    'ALIASES_OPTIONS': [],
change to `ALIAS` or `ALIAS_CMDS` for alias commands

2022-10-14 23:34 UTC, rujutashinde commented on teflo/utils/config.py
> +            if not section.startswith('aliases'):
this will change when you change it t alias

2022-10-21 15:51 UTC, rujutashinde requested changes

2022-10-21 15:51 UTC, rujutashinde commented on docs/users/quickstart.rst
> +Teflo allow the use of alias to run predefine commands(Similar to git)
allows    predefined

2022-10-21 15:51 UTC, rujutashinde commented on docs/users/quickstart.rst
> +    $ Teflo alias -al dev_run
this is either use command like` teflo alias  dev_run` OR `teflo -al dev_run `correct ? you dont have to pass both `alias` and `-al`

2022-10-21 15:51 UTC, rujutashinde commented on teflo/cli.py
> +              help="Run Teflo Predefine command from teflo.cfg alias block."
predefined

2022-10-21 15:51 UTC, rujutashinde commented on teflo/cli.py
> +@click.option("-al", "--alias",
Do we need this -al/alias switch ? it is not serving any purpose as your command name itself is alias.
could it be just `teflo alias <whatever the alias command name in the teflo.cfg>`
I am not sure if click provides with a way to allow a command with directly a value and not use an option/switch like you are doing now. If it is not available then change the option name to either `--cmd/-c` so when we run it looks like `teflo alias --cmd/-c <cmd name>` instead of ```teflo alias --alias <cmd name>```

2022-10-21 15:51 UTC, rujutashinde commented on tests/functional/test_cli.py
> +        """This test will check if FAILD when Aliases command provided Wrong task in the teflo.cfg """
typo FAILED

2022-10-25 15:09 UTC, rujutashinde approved these changes
just a spelling typo, rest LGTM, you can then merge . i am approving it now

2022-10-25 15:27 UTC, merged