fixed 250
RedHatQE/teflo pull request #251
Opened 2022-10-14 19:17 UTC by JunqiZhang0

2022-10-14 23:13 UTC, rujutashinde requested changes

2022-10-14 23:13 UTC, rujutashinde commented on teflo/cli.py
> +              # is_flag=True,
@JunqiZhang0  this is still not giving the output of parsing by_depth or by_level. below is my test

```
$ teflo show -s teflo_demo.yml -im by_level
--------------------------------------------------
Teflo Framework v2.2.7
Copyright (C) 2022, Red Hat, Inc.
--------------------------------------------------
2022-10-14 19:02:18,792 WARNING Scenario workspace was not set, therefore the workspace is automatically assigned to the current working directory. You may experience problems if files needed by teflo do not exists in the scenario workspace.
2022-10-14 19:02:18,852 WARNING Groups parameter was not set for asset host1_localhost.
An option needs to be given. See help
(temp_teflo_39_venv) [rushinde@rushinde tef_dem_22]$ teflo show -s teflo_demo.yml -im by_depth
--------------------------------------------------
Teflo Framework v2.2.7
Copyright (C) 2022, Red Hat, Inc.
--------------------------------------------------
2022-10-14 19:02:27,500 WARNING Scenario workspace was not set, therefore the workspace is automatically assigned to the current working directory. You may experience problems if files needed by teflo do not exists in the scenario workspace.
2022-10-14 19:02:27,561 WARNING Groups parameter was not set for asset host1_localhost.
An option needs to be given. See help
```

2022-10-14 23:13 UTC, rujutashinde commented on teflo/cli.py
>                )
The issue is you are not using` iterate_method `variable anywhere in the show command method in line 92, it needs to be used to perform the correct operation of displaying the graph

2022-10-14 23:20 UTC, rujutashinde commented on teflo/cli.py
>                )
Also modify the commit statement to something more appropriate

2022-10-18 00:30 UTC, JunqiZhang0 commented on teflo/cli.py
> +              # is_flag=True,
You need to add **--show-graph** tag to have it shown

2022-10-18 03:29 UTC, rujutashinde commented on teflo/cli.py
> +              # is_flag=True,
hmm it still does not use the `-im` or `--iterate-method` switch.  also the format needs to change in the help menu, `-im ` should be a part of the show-graph command and not an individual one, right now it seems like we need to provide it individually.

If i provide `by_depth` or `by_level`  it does not change the output . this is because the variable which is collecting the values for `-im` is not being used ahead in the code. look at `line 92 `in` cli.py`

```
(temp_teflo_39_venv) [rushinde@rushinde tef_dem_22]$ teflo show --show-graph -s teflo_demo.yml 
--------------------------------------------------
Teflo Framework v2.2.7
Copyright (C) 2022, Red Hat, Inc.
--------------------------------------------------
2022-10-17 23:24:31,996 WARNING Scenario workspace was not set, therefore the workspace is automatically assigned to the current working directory. You may experience problems if files needed by teflo do not exists in the scenario workspace.
2022-10-17 23:24:32,061 WARNING Groups parameter was not set for asset host1_localhost.
Below is the structure of the Scenario Definition Files


ITERATE METHOD: by_level




->teflo_demo.yml
   ->demo_execute.yml

(temp_teflo_39_venv) [rushinde@rushinde tef_dem_22]$ teflo show --show-graph -s teflo_demo.yml -im 
Error: Option '-im' requires an argument.
(temp_teflo_39_venv) [rushinde@rushinde tef_dem_22]$ teflo show --show-graph -s teflo_demo.yml -im by_depth
--------------------------------------------------
Teflo Framework v2.2.7
Copyright (C) 2022, Red Hat, Inc.
--------------------------------------------------
2022-10-17 23:24:54,545 WARNING Scenario workspace was not set, therefore the workspace is automatically assigned to the current working directory. You may experience problems if files needed by teflo do not exists in the scenario workspace.
2022-10-17 23:24:54,611 WARNING Groups parameter was not set for asset host1_localhost.
Below is the structure of the Scenario Definition Files


ITERATE METHOD: by_level




->teflo_demo.yml
   ->demo_execute.yml

```

2022-10-27 01:24 UTC, JunqiZhang0 commented
Transferred this issue to @guyyaakov1

2022-10-27 01:24 UTC, closed without merging