CCITCARBON-489 fix ans orch faile. update min python v3.9
RedHatQE/teflo pull request #265
Opened 2022-11-24 13:08 UTC by guyyaakov1

2022-11-24 13:49 UTC, ryankwilliams commented on setup.py
>          'Programming Language :: Python :: 3.6',
```suggestion
```

This classifier can be removed since the minimum python version supported now is `>=3.9`.

2022-11-24 13:59 UTC, ryankwilliams commented on setup.py
>          'ansible>=2.5.0',
While bumping the python version to minimum of 3.9, we probably should update the minimum version for ansible, as 2.5.0 is unmaintained [1]. When installing teflo, it's always going to be pulling in the latest ansible version which as of now is 7.0.0.

```suggestion
        'ansible>=7.0.0',
```

[1] https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-community-changelogs

2022-11-27 16:05 UTC, ryankwilliams commented on .github/workflows/run_unit_tests.yml
> +        - 'quay.io/gyaakov/ubi_py39'
@guyyaakov1 I see you are using a custom container image maintained by you. Just wondering why is that? Does the _ubi8/python-39_ not provide packages this job requires?

https://catalog.redhat.com/software/containers/ubi8/python-39/6065b24eb92fbda3a4c65d8f

2022-11-27 17:41 UTC, guyyaakov1 commented on .github/workflows/run_unit_tests.yml
> +        - 'quay.io/gyaakov/ubi_py39'
Thanks For the help!
Will let you know when i will update this images.

2022-11-28 09:49 UTC, rnetser commented on .github/workflows/run_unit_tests.yml
> +        - 'quay.io/gyaakov/ubi_py39'
@guyyaakov1 @ryankwilliams any reason why not to use centos-stream9?

2022-11-28 10:24 UTC, guyyaakov1 commented on .github/workflows/run_unit_tests.yml
> +        - 'quay.io/gyaakov/ubi_py39'
@rnetser is this img need to be pulled with docker creds?

2022-11-28 11:50 UTC, rnetser commented on .github/workflows/run_unit_tests.yml
> +        - 'quay.io/gyaakov/ubi_py39'
This is the image `quay.io/centos/centos:stream9`

2022-11-28 13:09 UTC, ryankwilliams commented on .github/workflows/run_unit_tests.yml
> +        - 'quay.io/gyaakov/ubi_py39'
@rnetser No specific reason, I saw @guyyaakov1 had `ubi` within his container image name and just was providing the standard ubi8 or even ubi9 image that could be used.

2022-11-28 16:30 UTC, rujutashinde requested changes

2022-11-28 16:30 UTC, rujutashinde commented on tests/functional/test_core_classes.py
> +    gv_path = os.path.join('/tmp/ws/ansible/group_vars/ans_gv.yml')
this will not work.
you are not joining anything here

2022-11-28 20:15 UTC, rujutashinde requested changes

2022-11-28 20:15 UTC, rujutashinde commented on tests/functional/test_teflo.py
> +def cleanup_master(request):
@guyyaakov1 i am not sure how you are using this fixture, it is calling cleanup_master() within he cleanup_master(request) method?

2022-11-28 20:15 UTC, rujutashinde commented on teflo/orchestrators/ext/ansible_orchestrator_plugin/ansible_orchestrator_plugin.py
> +        # self.logger.info('Executing playbook:')
remove this comment

2022-11-29 14:41 UTC, ryankwilliams commented on .github/workflows/run_unit_tests.yml
> +          yum install -y glibc-langpack-en gcc python3 python3-devel python3-pip krb5-workstation krb5-devel git
```suggestion
          dnf install -y glibc-langpack-en gcc python3 python3-devel python3-pip krb5-workstation krb5-devel git
```

2022-11-29 14:58 UTC, rujutashinde approved these changes
LGTM

2022-11-29 15:43 UTC, merged