fix get collection playbook
RedHatQE/teflo pull request #269
Opened 2023-02-01 11:36 UTC by guyyaakov1

2023-02-01 14:27 UTC, rujutashinde requested changes

2023-02-01 14:27 UTC, rujutashinde commented on teflo/ansible_helpers.py
> +            # u_coll_path = self.get_default_config(key="COLLECTIONS_PATHS")
if this is a comment please remove it

2023-02-01 14:27 UTC, rujutashinde commented on teflo/ansible_helpers.py
> +
Please add a one line/short comment of what is being done here

2023-02-01 14:27 UTC, rujutashinde commented on teflo/ansible_helpers.py
> +                    results2 = exec_local_cmd_pipe(f"ansible-galaxy {key} install -r {requirements_file} -p {u_path}",
there is no need to use a different variable here , since it is an if/else statement `results` should be able to hold one result or the other.
The code is repeated in this block , can you refactor it

2023-02-01 14:27 UTC, rujutashinde commented on teflo/ansible_helpers.py
> +
please provide description of what this method is doing

2023-02-01 14:27 UTC, rujutashinde commented on teflo/ansible_helpers.py
> +            jpath = os.path.join(con_coll_path[0], 'ansible_collections',
where is the variable `jpath` is being used?

2023-02-01 14:27 UTC, rujutashinde commented on teflo/orchestrators/ext/ansible_orchestrator_plugin/ansible_orchestrator_plugin.py
> +                    works_coll = os.path.join(self.config["WORKSPACE"], 'collections')
Rename this variable to `ws_collection_path` or `ws_coll_path`

2023-02-01 14:27 UTC, rujutashinde commented on tests/functional/test_ansible_helpers.py
> +    # @staticmethod
this test should work. it is basically what you are changing

2023-02-01 14:27 UTC, rujutashinde commented on tests/functional/test_ansible_helpers.py
> +    # @staticmethod
from the last run it looks more like a spacing issue and not a test issue
```

py3-unit: commands[1] /__w/teflo/teflo/tests/functional> pycodestyle ../../teflo
../../teflo/ansible_helpers.py:491:26: E225 missing whitespace around operator
                if key =='collection' and u_path:
                         ^
../../teflo/ansible_helpers.py:492:118: E203 whitespace before ','
                    results2 = exec_local_cmd_pipe(f"ansible-galaxy {key} install -r {requirements_file} -p {u_path}"
                                                                                                                     ^
../../teflo/ansible_helpers.py:538:5: E303 too many blank lines (2)
    def get_default_config(self, key=None):
    ^
1       E203 whitespace before ','
1       E225 missing whitespace around operator
1       E303 too many blank lines (2)
py3-unit: exit 1 (1.72 seconds) /__w/teflo/teflo/tests/functional> pycodestyle ../../teflo pid=1530
.pkg: _exit> python /usr/local/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
  py3-unit: FAIL code 1 (69.53=setup[45.91]+cmd[21.90,1.72] seconds)
  evaluation failed :( (69.64 seconds)
```

2023-02-06 15:58 UTC, dno-github approved these changes
LGTM

2023-02-06 17:37 UTC, merged