CCITCARBON-267 Allow jinja templating within teflo.cfg
RedHatQE/teflo pull request #51
Opened 2021-03-15 17:03 UTC by rujutashinde

* rectified task_concurrency method in helpers.py
* Added unit test to cover this change
* Added doc change in configuration.rst

2021-03-17 15:14 UTC, JunqiZhang0 requested changes

2021-03-17 16:37 UTC, rujutashinde commented on docs/users/configuration.rst
> +    auth_url=https://rhos-d.infra.prod.upshift.rdu2.redhat.com:13000
yup i will remove this and just put <auth_url> instead. good catch!

2021-03-17 17:35 UTC, rujutashinde commented on docs/users/configuration.rst
> +    auth_url=https://rhos-d.infra.prod.upshift.rdu2.redhat.com:13000
done

2021-03-17 21:10 UTC, shay6 approved these changes

2021-03-17 21:10 UTC, shay6 commented on docs/users/configuration.rst
> +    export OS_TENTAT=project1
s/TENTAT/TENANT

2021-03-17 21:27 UTC, rujutashinde commented on docs/users/configuration.rst
> +    export OS_TENTAT=project1
done

2021-03-18 13:24 UTC, JunqiZhang0 approved these changes

2021-03-18 14:49 UTC, merged