fix nested yaml vars
RedHatQE/teflo pull request #76
Opened 2021-06-07 19:12 UTC by JunqiZhang0

2021-06-08 18:49 UTC, rujutashinde reviewed
Couple of things:
1. Could you send me some test data that you tested this out with
2. Add this to one of the unit tests, as in change a unit test to work with variables which are recursively templated, e.g. maybe within test     <def test_valid_run_multiple_vars(mock_method, runner)> to use recursive templated data?
3. Edit the title of teh PR to add the CCITCARBON ticket number, so it is reflected in jira
4. If you are unable to add a unit test to test out this code, make sure you add this feature witin one of our integration job scenarios

2021-06-08 18:49 UTC, rujutashinde commented on teflo/helpers.py
> +            # import pdb; pdb.set_trace()
remove comment

2021-06-08 18:49 UTC, rujutashinde commented on teflo/helpers.py
> +            import pdb
place all imports in the beginning of the file

2021-06-08 18:49 UTC, rujutashinde commented on teflo/helpers.py
> +        # import pdb;pdb.set_trace()
remove comment

2021-06-08 18:49 UTC, rujutashinde commented on teflo/helpers.py
> +    # import pdb;pdb.set_trace()
remove comment

2021-06-08 18:49 UTC, rujutashinde commented on teflo/helpers.py
> +    for item in temp_data.items():
Add some comments as to what is being done here

2021-06-08 18:49 UTC, rujutashinde commented on teflo/helpers.py
> +
Add description for this method as to what it is doing

2021-06-17 04:49 UTC, rujutashinde requested changes
I ran the tests manually which went through fine with lists and additional variable files in differnt locations.

Also squash the commits

2021-06-17 04:49 UTC, rujutashinde commented on teflo/helpers.py
> +def validate_brakets(input):
the spelling of brackets

2021-06-17 04:49 UTC, rujutashinde commented on docs/users/variable_data.rst
> +Currently teflo supports nested variable using any of above methods
Currently teflo supports nested variable using any of **below** methods

change above to below

2021-06-17 04:49 UTC, rujutashinde commented on docs/users/variable_data.rst
> +You can
run make docs and check this output , as it is not seen in a proper format . It needs some spacing done correctly

2021-06-17 04:52 UTC, rujutashinde commented on docs/users/variable_data.rst
> +1. Use multiple layer nested vars
run make docs and check this output , as it is not seen in a proper format . It needs some spacing done correctly

2021-06-17 13:06 UTC, JunqiZhang0 commented on docs/users/variable_data.rst
> +Currently teflo supports nested variable using any of above methods
It should be above because I mean the documentation above

2021-06-17 13:07 UTC, JunqiZhang0 commented on docs/users/variable_data.rst
> +You can
Thanks!

2021-06-17 14:33 UTC, rujutashinde approved these changes
LGTM

2021-06-17 14:37 UTC, merged