CCITCARBON-217 create teflo init command
RedHatQE/teflo pull request #92
Opened 2021-06-28 21:41 UTC by shay6

2021-06-28 22:17 UTC, JunqiZhang0 commented on examples/teflo_init/README.rst
> +=====
Why do we need this file? Maybe move this to the docs/ folder?

2021-06-28 22:18 UTC, JunqiZhang0 commented on examples/teflo_init/ansible.cfg
> +# Example config file for ansible -- https://ansible.com/
We have existing examples repository here https://github.com/RedHatQE/teflo_examples, so you may want to use this one as the source of the examples

2021-06-28 22:19 UTC, JunqiZhang0 commented on examples/teflo_init/ansible/playbook_ip_info.yml
> +---
same problem for the examples

2021-06-28 22:19 UTC, JunqiZhang0 commented on examples/teflo_init/ansible/playbook_shell_cmd.yml
> +---
same problem for the examples

2021-06-28 22:21 UTC, JunqiZhang0 commented on teflo/cli.py
> +        dirname = 'teflo_init_project'
Would you think teflo_workspace is better?

2021-06-28 22:23 UTC, JunqiZhang0 commented on teflo/cli.py
> +    shutil.rmtree('.teflo_cache')
From line 341 to here, it could be put into a function, the code will look cleaner.

2021-06-28 22:24 UTC, JunqiZhang0 requested changes
We have existing examples repository here https://github.com/RedHatQE/teflo_examples, so you may want to use this one as the source of the examples. This way we don't need to maintain two places for examples

2021-06-28 22:44 UTC, shay6 commented on teflo/cli.py
> +        dirname = 'teflo_init_project'
yes, I will change it

2021-06-28 22:45 UTC, shay6 commented on teflo/cli.py
> +    shutil.rmtree('.teflo_cache')
will do

2021-06-28 22:47 UTC, shay6 commented on examples/teflo_init/README.rst
> +=====
you right. I can remove it. I also explained it in the docs/users/quickstart.rst file

2021-06-28 22:47 UTC, shay6 commented on examples/teflo_init/ansible.cfg
> +# Example config file for ansible -- https://ansible.com/
I'll move the examples to this repo

2021-06-29 10:17 UTC, shay6 commented on examples/teflo_init/README.rst
> +=====
done.
I added an explanation on the command in the docs

2021-06-29 10:17 UTC, shay6 commented on examples/teflo_init/ansible.cfg
> +# Example config file for ansible -- https://ansible.com/
done
I created a PR for it
https://github.com/RedHatQE/teflo_examples/pull/4

2021-06-29 10:18 UTC, shay6 commented on examples/teflo_init/ansible/playbook_ip_info.yml
> +---
done
I created a PR for it
https://github.com/RedHatQE/teflo_examples/pull/4

2021-06-29 10:18 UTC, shay6 commented on examples/teflo_init/ansible/playbook_shell_cmd.yml
> +---
done
I created a PR for it
https://github.com/RedHatQE/teflo_examples/pull/4

2021-06-29 10:18 UTC, shay6 commented on teflo/cli.py
> +        dirname = 'teflo_init_project'
done

2021-06-29 10:18 UTC, shay6 commented on teflo/cli.py
> +    shutil.rmtree('.teflo_cache')
done

2021-06-29 13:54 UTC, rujutashinde commented on teflo/cli.py
> +    click.echo("The teflo initial project created successfully")
Could you change this to teflo workspace created successfully instead?
the initial project could be misleading, as we are stating in the init command that we are creating a workspace

2021-06-29 13:54 UTC, rujutashinde commented on teflo/cli.py
> +    exec_local_cmd(cmd)
the exec_local_cmd method returns op.
We need to make sure the op is valid, just in case the execution of command caused any error.
Right now there is no error handling here

2021-06-30 09:26 UTC, shay6 commented on teflo/cli.py
> +    exec_local_cmd(cmd)
done

2021-06-30 12:39 UTC, shay6 commented
I updated the quickstart.rst file according to the new examples in the teflo_examples repo.
I added an error handling
I modified the message of successfull run from "teflon initial project" to "teflon workspace".

WIP --> need to add unit-tests

2021-07-01 19:36 UTC, rujutashinde reviewed
LGTM

2021-07-02 08:35 UTC, shay6 commented
we need to merge the teflo_examples [PR](https://github.com/RedHatQE/teflo_examples/pull/4) first, and then merge this one, because the examples held in the teflo_examples repo, as required.

2021-07-02 14:49 UTC, JunqiZhang0 approved these changes
LGTM

2021-07-06 13:17 UTC, rujutashinde approved these changes

2021-07-06 13:33 UTC, merged